export function toggleSettings() {
  const settingsDiv = document.getElementById('settings');
  const toggleButton = document.getElementById('toggleButton');
  settingsDiv.classList.toggle('collapsed');

  toggleButton.textContent = settingsDiv.classList.contains('collapsed')
    ? 'Show Settings'
    : 'Hide Settings';
}


export function resetSettings() {
  document.querySelectorAll('#settings input[type="checkbox"]').forEach(checkbox => {
    checkbox.checked = true;
  });
}

export function copyToClipboard() {
  const outputDiv = document.getElementById('output');
  const text = outputDiv.innerText;

  navigator.clipboard.writeText(text)
    .then(() => {
      const copyBtn = document.getElementById('copyBtn');
      const originalText = copyBtn.textContent;
      copyBtn.textContent = 'Copied!';

      setTimeout(() => {
        copyBtn.textContent = originalText;
      }, 2000);
    })
    .catch(err => {
      console.error('Failed to copy: ', err);
      alert('Failed to copy text to clipboard');
    });
}

export function printIsland() {
  const printContent = document.getElementById('output').innerHTML;
  const originalContent = document.body.innerHTML;

  document.body.innerHTML = `
    <div style="padding: 2em; font-family: sans-serif;">
      <h1 style="text-align: center; color: #2c4c26;">Island Details</h1>
      ${printContent}
      <div style="text-align: center; margin-top: 2em; font-size: 0.8em; color: #555;">
        Generated by Endless Isles Generator
      </div>
    </div>
  `;

  window.print();
  document.body.innerHTML = originalContent;
}

export function setupCollapsibles() {
  document.querySelectorAll(".collapsible").forEach(button => {
    button.addEventListener("click", () => {
      button.classList.toggle("active");
      const content = button.nextElementSibling;
      content.style.maxHeight = content.style.maxHeight ? null : content.scrollHeight + "px";
    });
  });
}
